//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("2.0.8")]
[assembly: AssemblyFileVersion("2.0.8")]
[assembly: AssemblyInformationalVersion("2.0.8")]
[assembly: AssemblyCopyright("Copyright © h82258652 2018 - 2020")]

